export enum ACTIONS {
  CLEAR_ERROR_BY_ACTION_TYPE = 'CLEAR_ERROR_BY_ACTION_TYPE',
  CLEAR_SUCCESS_BY_ACTION_TYPE = 'CLEAR_SUCCESS_BY_ACTION_TYPE',
  CLEAR_LOADING_BY_ACTION_TYPE = 'CLEAR_LOADING_BY_ACTION_TYPE',
}
