export enum ACTIONS {
  CLEAR_ERROR_BY_ACTION_TYPE = 'CLEAR_ERROR_BY_ACTION_TYPE',
  CLEAR_SUCCESS_BY_ACTION_TYPE = 'CLEAR_SUCCESS_BY_ACTION_TYPE',
  CLEAR_LOADING_BY_ACTION_TYPE = 'CLEAR_LOADING_BY_ACTION_TYPE',
  REMOVE_REDUCER_BY_ID = 'REMOVE_REDUCER_BY_ID',
}

export const REDUCER_ID_PROPERTY_NAME = 'reducerId';
export const ACTION_META_PROPERT_NAME = 'meta';
